---
title: "MeLMSens analysis"
output: html_notebook
---


```{r load_data, echo = FALSE}
dataBasePath = file.path('~','Dropbox (Aguirre-Brainard Lab)','MELA_data','Experiments','OLApproach_Psychophysics','MeLMSens')
participantID = 'HERO_JXV'
sessionDate = '2018-04-16'
sessionName = 'pilot_1'
sessionID = sprintf('%s_%s',sessionDate,sessionName)
dataFilePath = file.path(dataBasePath,participantID,sessionID,sprintf('results-%s-%s.csv',participantID,sessionName))
sessionData = read.csv(dataFilePath, header = TRUE, strip.white=FALSE, stringsAsFactors = TRUE)
```

```{r}
library(ggplot2)
ggplot(sessionData, aes(x=flickerLag,y=flickerContrastNominal, color=pulseContrastNominal)) +
  geom_point() +
  scale_x_continuous(limits=c(-1,max(sessionData$pulseDuration))) +
  scale_y_continuous(limits=c(0,.05)) +
  labs(title = 'LMS detection threshold, on melanopic backgrounds', x = 'Onset of LMS flicker\n(s, relative to onset of melanopsin pulse)', y = 'LMS flicker contrast (targeted)', color = 'Melanopsin contrast\n(targeted)')
```