function acquisitions = makeAcquisitions(directions, receptors, varargin)
%MAKEACQUISITIONST Summary of this function goes here
%   Detailed explanation goes here
%% Parse input
parser = inputParser;
parser.addRequired('directions');
parser.addRequired('receptors');
parser.addParameter('adaptationDuration',minutes(5));
parser.addParameter('NTrialsPerStaircase',40);
parser.parse(directions, receptors, varargin{:});

%% Low Mel
acquisitions(1) = acquisition(...
    directions('Mel_low'),...
    directions('FlickerDirection_Mel_low'),...
    receptors,...
    'name',"Mel_low");

%% High Mel
acquisitions(2) = acquisition(...
    directions('Mel_high'),...
    directions('FlickerDirection_Mel_high'),...
    receptors,...
    'name',"Mel_high");

%% Low LMS
acquisitions(3) = acquisition(...
    directions('LMS_low'),...
    directions('FlickerDirection_LMS_low'),...
    receptors,...
    'name',"LMS_low");

%% High LMS
acquisitions(4) = acquisition(...
    directions('LMS_high'),...
    directions('FlickerDirection_LMS_high'),...
    receptors,...
    'name',"LMS_high");

%% Combine
rngSettings = rng('shuffle');
acquisitions = Shuffle(acquisitions);

%% Override params
for i = 1:4
    acquisitions(i).NTrialsPerStaircase = parser.Results.NTrialsPerStaircase;
    acquisitions(i).adaptationDuration = parser.Results.adaptationDuration;
end
    
end