---
title: "MeLMSens initial data analysis"
author: "Joris Vincent"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: no
  html_notebook:
    number_sections: yes
    toc: yes
  html_document:
    toc: yes
---
```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
```
```{r merge, echo=FALSE}
csvspath = "../../data/processed/"
csvfiles = list.files(csvspath, recursive = TRUE, pattern = ".*.csv")
results_all = lapply(csvfiles,function(x) {
   read_csv(paste0(csvspath,x), col_types = cols())
  }) %>%
  bind_rows
```
```{r munge, echo=FALSE}
#results_all = read_csv('../../data/processed/results_all.csv',col_types=cols())
results_all = results_all %>%
  separate(datafile,into=c("tmp1","participant","session","tmp2"),sep="-") %>%
  select(-tmp1, -tmp2)

# Filter out pilot sessions
results_all = results_all %>%
  filter(session != "pilot_1")

# Recode adaptationLevel as factor
results_all = mutate(results_all,adaptationLevel=factor(results_all$adaptationLevel,levels=c('low','high')))
```

```{r echo=FALSE}
# Average over sessions
results_avg = results_all %>% 
  group_by(participant, axis, adaptationLevel) %>%
  summarise(
    nominalThresholdContrast = median(nominalThresholdContrast, na.rm = TRUE), 
    SEMNominalThresholdContrast = 1.253*sd(.$nominalThresholdContrast, na.rm = TRUE)/sqrt(n()),
    validatedThresholdContrast = median(validatedThresholdContrast, na.rm = TRUE),
    SEMValidatedThresholdContrast = 1.253*sd(.$validatedThresholdContrast, na.rm = TRUE)/sqrt(n()),
    nominalJND = median(nominalJND, na.rm = TRUE),
    SEMNominalJND = 1.253*sd(.$nominalJND, na.rm = TRUE)/sqrt(n()),
    validatedJND = median(validatedJND, na.rm = TRUE),
    SEMValidatedJND = 1.253*sd(.$validatedJND, na.rm = TRUE)/sqrt(n()),
    session = 'mean'
  )
```
# Plots
## Nominal JNDs
```{r plot_participant_nominal_JNDs, echo=FALSE}
results_all %>%
  ggplot() +
  aes(adaptationLevel, nominalJND, group=interaction(session,axis),color=axis) +
  geom_line(alpha = .4) +
  geom_line(data = results_avg, size = 1) +
  geom_pointrange(data = results_avg, aes(ymax = nominalJND+SEMNominalJND, ymin = nominalJND-SEMNominalJND)) +
  facet_wrap( ~ participant) +
  ylab("Nominal JND") +
  xlab("Adaptation level") +
  theme_minimal()
```
\pagebreak

## Validated JNDs
```{r plot_participant_validated_JNDs, echo=FALSE}
results_all %>%
  ggplot() +
  aes(adaptationLevel, validatedJND, group=interaction(session,axis),color=axis) +
  geom_line(alpha = .4) +
  geom_line(data = results_avg, size = 1) +
  geom_pointrange(data = results_avg, aes(ymax = validatedJND+SEMValidatedJND, ymin = nominalJND-SEMValidatedJND)) +
  facet_wrap( ~ participant) +
  ylab("Validated JND") +
  xlab("Adaptation level") +
  theme_minimal()
```
\pagebreak

## Nominal threshold contrasts
```{r plot_participant_nominal_contrasts, echo=FALSE}
results_all %>%
  ggplot() +
  aes(adaptationLevel, nominalThresholdContrast, group=interaction(session,axis),color=axis) +
  geom_line(alpha = .4) +
  geom_line(data = results_avg, size = 1) +
  geom_pointrange(data = results_avg, aes(ymax = nominalThresholdContrast+SEMNominalThresholdContrast, ymin = nominalThresholdContrast-SEMNominalThresholdContrast)) +
  facet_wrap( ~ participant)  +
  ylab("Nominal threshold contrast (fraction)") +
  xlab("Adaptation level") +
  theme_minimal()
```
\pagebreak

## Validated threshold contrasts
```{r plot_participant_validated_contrasts, echo=FALSE}
results_all %>%
  ggplot() +
  aes(adaptationLevel, validatedThresholdContrast, group=interaction(session,axis),color=axis) +
  geom_line(alpha = .4) +
  geom_line(data = results_avg, size = 1) +
  geom_pointrange(data = results_avg, aes(ymax = validatedThresholdContrast+SEMValidatedThresholdContrast, ymin = validatedThresholdContrast-SEMValidatedThresholdContrast)) +
  facet_wrap( ~ participant) +
  ylab("Validated threshold contrast (fraction)") +
  xlab("Adaptation level") +
  theme_minimal()
```

# Statistics
```{r summary_statistics, tidy=TRUE, echo=FALSE, eval=FALSE}
ttests = results_all %>% 
  select(participant, adaptation, axis, excitationPos_LMS_diff) %>%
  gather(key = variable, value = value, -adaptation, -axis, -participant) %>%
  group_by(participant, adaptation, axis, variable) %>%
  summarise(value = list(value)) %>%
  spread(adaptation, value) %>%
  group_by(participant, axis) %>%
  mutate(t_value = t.test(unlist(high),unlist(low),paired=TRUE)$statistic,
         p_value = t.test(unlist(high),unlist(low),paired=TRUE)$p.value) %>%
  select(participant, axis, t_value, p_value)

results_mean %>% 
  gather(variable, value, -participant, -axis, -adaptation) %>%
  unite(temp, adaptation, variable) %>%
  spread(temp, value) %>%
  rename(low = low_mean_excitation_LMS_diff_pos,high = high_mean_excitation_LMS_diff_pos) %>%
  select(participant, axis, low, high, low_sem, high_sem) %>%
  full_join(.,ttests,by=c('participant','axis')) %>%
  kable(digits = 4)
```