---
title: "MeLMSens initial data analysis"
author: "Joris Vincent"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: no
  html_notebook:
    number_sections: yes
    toc: yes
  html_document:
    toc: yes
---
```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
library(stringr)
source('../lib/median_SEM.R')
```
```{r merge, echo=FALSE}
csvsPath = normalizePath("../../data/processed")
csvfiles = list.files(csvsPath, recursive = TRUE, pattern = 'results_.*.csv')

results_all = lapply(csvfiles,function(x) {
   read_csv(file.path(csvsPath,x), col_types = cols())
  }) %>%
  bind_rows
```
```{r munge, echo=FALSE}
results_all = results_all %>%
  separate(datafile,into=c("tmp1","participant","session","tmp2"),sep="-") %>%
  select(-tmp1, -tmp2) %>%

  # Recode adaptationLevel as factor
  mutate(adaptationLevel= factor(adaptationLevel,levels=c('low','high'))) %>%

  # Rename participants
  mutate(participant = str_replace(participant,'HERO_','')) %>%

  # Rename sessions
  mutate(session = str_replace(session,'session_',''))
```
## Plot
```{r normalize_JNDs, echo=FALSE}
JNDs = results_all %>%
  # Convert to wide-format: separate columns for high/low, nominal/measured JND
  select(-quickThresholdContrast, -nominalThresholdContrast, -validatedThresholdContrast) %>%
  unite(nominalJND,validatedJND, col = "JND") %>%
  spread(key = adaptationLevel, value = JND) %>%
  separate(low, into = c('low_nominal','low_measured'), sep = "_", convert=TRUE) %>%
  separate(high, into = c('high_nominal','high_measured'), sep = "_", convert=TRUE) %>%

  # Normalize to median(low_nominal) -- median across sessions per participant per axis
  group_by(participant,axis) %>%
  mutate(low_measured = low_measured/median(low_nominal),
         high_nominal = high_nominal/median(low_nominal),
         high_measured = high_measured/median(low_nominal),
         low_nominal = low_nominal/median(low_nominal))
```
```{r plot_JNDs, echo=FALSE}
JNDs %>% 
  # Convert back to tall: separate columns for measured and nominalJND, but separate rows for high/low
  unite(low_nominal,low_measured,col='low') %>%
  unite(high_nominal,high_measured,col='high') %>%
  gather(low,high,key='adaptationLevel',value='JND') %>%
  separate(JND, into=c('nominalJND','measuredJND'), sep = "_", convert=TRUE) %>%
  mutate(adaptationLevel=factor(adaptationLevel,levels=c('low','high'))) %>%

  # Plot
  ggplot() +
  aes(x = adaptationLevel) +
  facet_grid(participant ~ axis) +
  ylab("Just Noticeable LMS Difference \n(normalized to participant-median of low condition)") +
  xlab("Adaptation level") +
  theme_bw() +
  
  # Individual sessions
  geom_line(mapping = aes(y = nominalJND, group=session, color = 'nominal'), alpha = .4) +
  geom_line(mapping = aes(y = measuredJND, group=session, color = 'measured'), alpha = .4) +
  
  # Medians over sessions
  stat_summary(mapping = aes(x = adaptationLevel, y = nominalJND, group=1, color = 'nominal'),
               fun.y = median,
               size = 1,
               geom = "line",
               na.rm=TRUE) +
  stat_summary(mapping = aes(x = adaptationLevel, y = measuredJND, group=1, color = 'measured'),
               fun.y = median,
               size = 1,
               geom = "line",
               na.rm=TRUE) +
  
  # Point ranges median +- SEM(edian)
  geom_pointrange(mapping = aes(y = nominalJND, color = 'nominal'),
              stat="summary",
              fun.y = median,
              fun.ymin = medianMinusSEM,
              fun.ymax = medianPlusSEM,
              na.rm=TRUE) +  
  geom_pointrange(mapping = aes(y = measuredJND, color = 'measured'),
              stat="summary",
              fun.y = median,
              fun.ymin = medianMinusSEM,
              fun.ymax = medianPlusSEM,
              na.rm=TRUE)
```

\pagebreak

## Summary table
```{r table_JNDs, echo=FALSE}
JNDs %>% 
  # Convert back to tall: separate columns for high/low, but separate rows for nominal/measured
  unite(low_nominal,high_nominal,col='nominal') %>%
  unite(low_measured,high_measured,col='measured') %>%
  gather(nominal,measured,key = 'measured',value='JND', factor_key = FALSE) %>%
  separate(JND, into=c('low','high'), sep='_', convert=TRUE) %>%
  mutate(measured = factor(measured, levels = c('nominal','measured'))) %>%
  
  group_by(participant, axis, measured) %>%
  summarise(p = t.test(high,low,paired=TRUE)$p.value,
            t = t.test(high,low,paired=TRUE)$statistic,
            low_sem = SEMedian(low),
            high_sem = SEMedian(high),
            low = median(low, na.rm=TRUE),
            high = median(high, na.rm=TRUE)) %>%
  arrange(measured, axis) %>%
  select(participant, axis, measured, low, low_sem, high, high_sem, t, p) %>%
  kable(digits = 4)
```

\pagebreak

## Nominal vs. measured JND plot
```{r echo = FALSE}
JNDs %>%
  ggplot() +
  aes(x = low_nominal, xend = high_nominal, y = low_measured, yend = high_measured) +
  facet_grid(participant ~ axis) +
  xlab("Nominal LMS JND\n(normalized to participant-median of low condition)") +
  ylab("measured LMS JND\n(normalized to nominal participant-median of low condition)") +
  scale_x_continuous(limits = c(0,8)) +
  scale_y_continuous(limits = c(0,8)) +
  theme_bw() +
  coord_fixed(ratio = 1) +
  
  # Plot individual sessions
  geom_segment(arrow = arrow(length = unit(0.03,"npc")), alpha = .8) +

  # Guides
  geom_abline(slope = 1, intercept = 0, alpha = .5, linetype = 'dashed') +
  geom_hline(yintercept = 3.5, alpha = .5, linetype = 'dashed') +
  geom_vline(xintercept = 3.5, alpha = .5, linetype = 'dashed')
```

```{r plot_contrasts, eval = FALSE, echo=FALSE}
results_all %>%
  ggplot() +
  aes(x = adaptationLevel) +
  facet_grid(participant ~ axis) +
  ylab("LMS contrast at detection threshold (ratio)") +
  xlab("Adaptation level") +
  theme_bw() +
  
  # Individual sessions
  geom_line(mapping = aes(y = nominalThresholdContrast, group=session, color = 'nominal'), alpha = .4) +
  geom_line(mapping = aes(y = measuredThresholdContrast, group=session, color = 'measured'), alpha = .4) +
  
  # Medians over sessions
  stat_summary(mapping = aes(x = adaptationLevel, y = nominalThresholdContrast, group=1, color = 'nominal'),
               fun.y = median,
               size = 1,
               geom = "line",
               na.rm=TRUE) +
  stat_summary(mapping = aes(x = adaptationLevel, y = measuredThresholdContrast, group=1, color = 'measured'),
               fun.y = median,
               size = 1,
               geom = "line",
               na.rm=TRUE) +
  
  # Point ranges median +- SEM(edian)
  geom_pointrange(mapping = aes(y = nominalThresholdContrast, color = 'nominal'),
              stat="summary",
              fun.y = median,
              fun.ymin = medianMinusSEM,
              fun.ymax = medianPlusSEM,
              na.rm=TRUE) +  
  geom_pointrange(mapping = aes(y = measuredThresholdContrast, color = 'measured'),
              stat="summary",
              fun.y = median,
              fun.ymin = medianMinusSEM,
              fun.ymax = medianPlusSEM,
              na.rm=TRUE)
```

```{r table_Contrasts, eval = FALSE, echo=FALSE}
results_all %>%
  select(-nominalJND, -measuredJND, -quickThresholdContrast) %>%
  gather(key = "measured", value = "thresholdContrast", nominalThresholdContrast, measuredThresholdContrast) %>%
  spread(adaptationLevel, thresholdContrast) %>%
  mutate(measured = str_replace(measured,'ThresholdContrast','')) %>%
  group_by(participant, axis, measured) %>%
  summarise(p_value = t.test(high,low,paired=TRUE)$p.value,
            t_value = t.test(high,low,paired=TRUE)$statistic,
            low_SEM = SEMedian(low),
            high_SEM = SEMedian(high),
            low_median = median(low, na.rm=TRUE),
            high_median = median(high, na.rm=TRUE)) %>%
  arrange(measured, axis) %>%
  select(participant, axis, measured, low_median, low_SEM, high_median, high_SEM, t_value, p_value) %>%
  kable(digits = 4)
```